### PR TITLE
fixes: #{$13}

### PR DESCRIPTION
**Pull request by Sourz-101**
Added Binary Search Algo with detailed explanation Please accept my PR under the label of hacktoberfest-accepted.  Thank you :)

### CODE REVIEW

**Comment by 7sakshi7** [comment]
Please add an approach and detailed explanation.

**Comment by Sourz-101** [comment]
it is already mentioned

**Comment by 7sakshi7** [comment]
You have just written the code and added comments. That is not what I Am asking. Pls check the other 2 files. You will get idea from them.

**Comment by Sourz-101** [comment]
added approach and detailed explanation

**Comment by Sourz-101** [comment]
please label it as hacktoberfest so it can be counted in the hacktoberfest
thankyou

**Pull request merged**
